/* ═══════════════════════════════════════════════════════════
   INVOICING & COMMISSION QUOTES

   Adapted from wpwwhimself/muzyka-szyta-na-miare — a Laravel CRM for a music
   commission business whose core ideas were: commission *phases* visible to
   the client, automated expiry on quotes, and generated invoices. This module
   implements the invoice/quote generation half in pure client-side jsPDF,
   matching the existing look of lib/pdf.ts (black header, courier body).

   Run-book: knowledge/operations/COMMISSION_PIPELINE.md
═══════════════════════════════════════════════════════════ */

import { jsPDF } from "jspdf";

export interface InvoiceLine {
  description: string;
  quantity: number;
  unitPrice: number;
}

export interface InvoiceDoc {
  number: string;
  clientName: string;
  clientEmail?: string;
  issueDate: string;
  dueDate?: string;
  currency: string;
  taxRate: number; // 0.14 = 14%
  lines: InvoiceLine[];
  notes?: string;
  /** amount already received (deposit); drives the "balance due" line */
  paid?: number;
  from?: { name: string; email: string; address?: string };
}

export interface InvoiceTotals {
  subtotal: number;
  tax: number;
  total: number;
  balance: number;
}

export function invoiceTotals(inv: InvoiceDoc): InvoiceTotals {
  const subtotal = inv.lines.reduce(
    (s, l) => s + (Number(l.quantity) || 0) * (Number(l.unitPrice) || 0),
    0,
  );
  const tax = subtotal * (Number(inv.taxRate) || 0);
  const total = subtotal + tax;
  return {
    subtotal: round2(subtotal),
    tax: round2(tax),
    total: round2(total),
    balance: round2(total - (Number(inv.paid) || 0)),
  };
}

const round2 = (n: number) => Math.round(n * 100) / 100;

export function money(n: number, currency: string) {
  return `${currency} ${n.toLocaleString(undefined, {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;
}

/** Next sequential invoice number, e.g. INV-0007 */
export function nextInvoiceNumber(existing: string[]): string {
  const max = existing
    .map((n) => Number((n.match(/(\d+)\s*$/) || [])[1] ?? 0))
    .reduce((a, b) => Math.max(a, b), 0);
  return `INV-${String(max + 1).padStart(4, "0")}`;
}

/** Days until due; negative means overdue. Null when there is no due date. */
export function daysUntilDue(dueDate?: string): number | null {
  if (!dueDate) return null;
  const d = new Date(dueDate).getTime();
  if (Number.isNaN(d)) return null;
  return Math.ceil((d - Date.now()) / 86_400_000);
}

export function isOverdue(inv: { dueDate?: string; status: string }): boolean {
  if (inv.status === "Paid" || inv.status === "Void") return false;
  const d = daysUntilDue(inv.dueDate);
  return d !== null && d < 0;
}

/* ── PDF ─────────────────────────────────────────────────── */

function header(doc: jsPDF, eyebrow: string, title: string) {
  doc.setFillColor(10, 10, 12);
  doc.rect(0, 0, 210, 46, "F");
  doc.setTextColor(150);
  doc.setFont("courier", "normal");
  doc.setFontSize(9);
  doc.text(eyebrow.toUpperCase(), 16, 20);
  doc.setTextColor(255);
  doc.setFont("courier", "bold");
  doc.setFontSize(22);
  doc.text(title, 16, 33);
  doc.setDrawColor(255);
  doc.setLineWidth(0.8);
  doc.circle(190, 23, 1.4, "F");
  doc.line(190, 23, 190, 18);
  doc.line(190, 23, 195, 23);
}

function footer(doc: jsPDF, note?: string) {
  doc.setTextColor(150);
  doc.setFont("courier", "normal");
  doc.setFontSize(8);
  if (note) doc.text(doc.splitTextToSize(note, 178), 16, 274);
  doc.text("Generated by RIPPL · Built by Zeyad Sayedin · © 2026", 16, 288);
}

function label(doc: jsPDF, text: string, y: number, x = 16) {
  doc.setTextColor(120);
  doc.setFont("courier", "normal");
  doc.setFontSize(8);
  doc.text(text.toUpperCase(), x, y);
}

function value(doc: jsPDF, text: string, y: number, x = 16, size = 11) {
  doc.setTextColor(20);
  doc.setFont("courier", "bold");
  doc.setFontSize(size);
  doc.text(text, x, y);
}

export function invoicePdf(inv: InvoiceDoc) {
  const doc = new jsPDF();
  const t = invoiceTotals(inv);

  header(doc, "Invoice", inv.number);

  let y = 60;
  label(doc, "Billed to", y);
  value(doc, inv.clientName || "—", y + 7);
  if (inv.clientEmail) {
    doc.setFont("courier", "normal");
    doc.setFontSize(9);
    doc.setTextColor(90);
    doc.text(inv.clientEmail, 16, y + 14);
  }

  label(doc, "Issued", y, 120);
  value(doc, inv.issueDate || "—", y + 7, 120, 10);
  label(doc, "Due", y + 16, 120);
  value(doc, inv.dueDate || "On receipt", y + 23, 120, 10);

  y += 40;

  // table head
  doc.setDrawColor(200);
  doc.line(16, y, 194, y);
  y += 7;
  doc.setTextColor(120);
  doc.setFont("courier", "normal");
  doc.setFontSize(8);
  doc.text("DESCRIPTION", 16, y);
  doc.text("QTY", 128, y, { align: "right" });
  doc.text("RATE", 158, y, { align: "right" });
  doc.text("AMOUNT", 194, y, { align: "right" });
  y += 4;
  doc.line(16, y, 194, y);
  y += 9;

  doc.setTextColor(20);
  doc.setFontSize(10);
  inv.lines.forEach((l) => {
    const amount = (Number(l.quantity) || 0) * (Number(l.unitPrice) || 0);
    const wrapped = doc.splitTextToSize(l.description || "—", 100) as string[];
    doc.setFont("courier", "normal");
    doc.text(wrapped, 16, y);
    doc.text(String(l.quantity ?? 0), 128, y, { align: "right" });
    doc.text(money(Number(l.unitPrice) || 0, inv.currency), 158, y, { align: "right" });
    doc.setFont("courier", "bold");
    doc.text(money(round2(amount), inv.currency), 194, y, { align: "right" });
    y += Math.max(wrapped.length * 5, 9);
  });

  doc.setDrawColor(200);
  doc.line(120, y, 194, y);
  y += 9;

  const row = (k: string, v: string, bold = false) => {
    doc.setFont("courier", bold ? "bold" : "normal");
    doc.setFontSize(bold ? 12 : 10);
    doc.setTextColor(bold ? 20 : 90);
    doc.text(k, 120, y);
    doc.setTextColor(20);
    doc.text(v, 194, y, { align: "right" });
    y += bold ? 11 : 8;
  };

  row("Subtotal", money(t.subtotal, inv.currency));
  if (inv.taxRate > 0) row(`Tax ${(inv.taxRate * 100).toFixed(0)}%`, money(t.tax, inv.currency));
  row("Total", money(t.total, inv.currency), true);
  if (inv.paid) {
    row("Paid", `− ${money(round2(inv.paid), inv.currency)}`);
    row("Balance due", money(t.balance, inv.currency), true);
  }

  y += 8;
  if (inv.notes) {
    label(doc, "Notes", y);
    doc.setFont("courier", "normal");
    doc.setFontSize(9);
    doc.setTextColor(60);
    doc.text(doc.splitTextToSize(inv.notes, 178), 16, y + 7);
  }

  footer(
    doc,
    inv.from
      ? `${inv.from.name} · ${inv.from.email}${inv.from.address ? ` · ${inv.from.address}` : ""}`
      : undefined,
  );
  doc.save(`${inv.number}_${inv.clientName.replace(/\s+/g, "_")}.pdf`);
}

export interface QuoteDoc {
  number: string;
  clientName: string;
  title: string;
  currency: string;
  amount: number;
  depositPct: number; // 0.5
  validUntil: string;
  revisionsIncluded: number;
  included: string[];
  excluded: string[];
  rights?: string;
  notes?: string;
}

export function quotePdf(q: QuoteDoc) {
  const doc = new jsPDF();
  header(doc, "Commission Quote", q.title || q.number);

  let y = 60;
  label(doc, "Client", y);
  value(doc, q.clientName || "—", y + 7);
  label(doc, "Quote no.", y, 120);
  value(doc, q.number, y + 7, 120, 10);
  label(doc, "Valid until", y + 16, 120);
  value(doc, q.validUntil || "—", y + 23, 120, 10);
  y += 40;

  const section = (heading: string, items: string[]) => {
    label(doc, heading, y);
    y += 7;
    doc.setFont("courier", "normal");
    doc.setFontSize(10);
    doc.setTextColor(30);
    (items.length ? items : ["—"]).forEach((i) => {
      const w = doc.splitTextToSize(`• ${i}`, 178) as string[];
      doc.text(w, 16, y);
      y += w.length * 5 + 2;
    });
    y += 6;
  };

  section("What is included", q.included);
  section("What is not included", q.excluded);

  label(doc, "Revisions", y);
  value(doc, `${q.revisionsIncluded} rounds included; further rounds quoted separately`, y + 7, 16, 10);
  y += 22;

  if (q.rights) {
    label(doc, "Rights granted", y);
    doc.setFont("courier", "normal");
    doc.setFontSize(10);
    doc.setTextColor(30);
    doc.text(doc.splitTextToSize(q.rights, 178), 16, y + 7);
    y += 24;
  }

  doc.setDrawColor(200);
  doc.line(16, y, 194, y);
  y += 10;

  const deposit = round2(q.amount * q.depositPct);
  doc.setFont("courier", "normal");
  doc.setFontSize(10);
  doc.setTextColor(90);
  doc.text("Total fee", 16, y);
  doc.setTextColor(20);
  doc.setFont("courier", "bold");
  doc.setFontSize(12);
  doc.text(money(round2(q.amount), q.currency), 194, y, { align: "right" });
  y += 11;
  doc.setFont("courier", "normal");
  doc.setFontSize(10);
  doc.setTextColor(90);
  doc.text(`Deposit (${Math.round(q.depositPct * 100)}%) — due before work starts`, 16, y);
  doc.setTextColor(20);
  doc.text(money(deposit, q.currency), 194, y, { align: "right" });
  y += 9;
  doc.setTextColor(90);
  doc.text("Balance — due on delivery", 16, y);
  doc.setTextColor(20);
  doc.text(money(round2(q.amount - deposit), q.currency), 194, y, { align: "right" });
  y += 18;

  doc.setFont("courier", "normal");
  doc.setFontSize(8);
  doc.setTextColor(90);
  doc.text(
    doc.splitTextToSize(
      "Terms: work begins only after the deposit clears. Client review window is 7 days per delivery; " +
        "silence is treated as acceptance. Any change to the scope above triggers a new quote. " +
        "This quote expires on the date shown.",
      178,
    ),
    16,
    y,
  );
  y += 24;

  doc.setDrawColor(180);
  doc.line(16, y, 90, y);
  doc.line(110, y, 184, y);
  doc.setFontSize(8);
  doc.setTextColor(120);
  doc.text("Accepted by — Signature", 16, y + 5);
  doc.text("Date", 110, y + 5);

  footer(doc);
  doc.save(`${q.number}_${(q.clientName || "quote").replace(/\s+/g, "_")}.pdf`);
}
