import { jsPDF } from "jspdf";
import type { Artist, Release } from "./os-store";
import type { Campaign, ChecklistPhase } from "./campaign-data";

export interface SplitEntry {
  name: string;
  role: string;
  ipi?: string;        // IPI/CAE composer ID
  publisher?: string;  // publishing admin
  masterPct: number;   // master recording ownership %
  pubPct: number;      // publishing / composition %
  email?: string;
}
export interface SplitSheetInput {
  trackTitle: string;
  artist: string;
  isrc?: string;
  iswc?: string;
  recordingDate?: string;
  label?: string;
  publisher?: string;
  date: string;
  entries: SplitEntry[];
}

/* Client-facing PDF generators (press kit, release one-pager). Minimal,
   monospace-ish, on-brand black/white layout. */

function header(doc: jsPDF, eyebrow: string, title: string) {
  doc.setFillColor(10, 10, 12); doc.rect(0, 0, 210, 46, "F");
  doc.setTextColor(150); doc.setFont("courier", "normal"); doc.setFontSize(9);
  doc.text(eyebrow.toUpperCase(), 16, 20);
  doc.setTextColor(255); doc.setFont("courier", "bold"); doc.setFontSize(22);
  doc.text(title, 16, 33);
  // ripple mark
  doc.setDrawColor(255); doc.setLineWidth(0.8);
  doc.circle(190, 23, 1.4, "F");
  doc.line(190, 23, 190, 18); doc.line(190, 23, 195, 23);
}
function footer(doc: jsPDF) {
  doc.setTextColor(150); doc.setFont("courier", "normal"); doc.setFontSize(8);
  doc.text("Generated by RIPPL · Built by Zeyad Sayedin · © 2026", 16, 288);
}
function label(doc: jsPDF, text: string, y: number) {
  doc.setTextColor(120); doc.setFont("courier", "normal"); doc.setFontSize(8);
  doc.text(text.toUpperCase(), 16, y);
}
function value(doc: jsPDF, text: string, y: number, size = 13) {
  doc.setTextColor(20); doc.setFont("courier", "bold"); doc.setFontSize(size);
  doc.text(text, 16, y);
}

export function pressKitPdf(a: Artist) {
  const doc = new jsPDF();
  header(doc, "Press Kit", a.name);
  let y = 62;
  label(doc, "Type", y); value(doc, a.kind, y + 7); y += 22;
  label(doc, "Handle", y); value(doc, a.handle || "—", y + 7); y += 22;
  label(doc, a.kind === "Music" ? "Streams" : "Followers", y); value(doc, (a.kind === "Music" ? a.streams : a.followers) || "—", y + 7, 20); y += 24;
  label(doc, "Stage", y); value(doc, a.stage, y + 7); y += 24;
  label(doc, "Bio / Notes", y); y += 8;
  doc.setTextColor(40); doc.setFont("courier", "normal"); doc.setFontSize(11);
  const bio = a.note || `${a.name} is a leading ${a.kind.toLowerCase()} talent managed by RIPPL, with strong regional pull across TikTok, Instagram and DSPs.`;
  doc.text(doc.splitTextToSize(bio, 178), 16, y);
  footer(doc);
  doc.save(`${a.name.replace(/\s+/g, "_")}_Press_Kit.pdf`);
}

export function releaseOnePagerPdf(r: Release) {
  const doc = new jsPDF();
  header(doc, "Release One-Pager", r.title);
  let y = 62;
  label(doc, "Artist", y); value(doc, r.artist || "—", y + 7); y += 22;
  label(doc, "Release date", y); value(doc, r.releaseDate || "TBC", y + 7); y += 22;
  const dsps = [r.dsp.spotify && "Spotify", r.dsp.anghami && "Anghami", r.dsp.youtube && "YouTube"].filter(Boolean).join(" · ") || "—";
  label(doc, "Available on", y); value(doc, dsps, y + 7); y += 22;
  label(doc, "ISRC / UPC", y); value(doc, `${r.isrc || "—"}  ·  ${r.upc || "—"}`, y + 7, 11); y += 22;
  label(doc, "Audio QA", y);
  value(doc, `Dolby Atmos ${r.qa.atmos ? "✓" : "—"}   Master EQ ${r.qa.eq ? "✓" : "—"}`, y + 7, 11); y += 24;
  label(doc, "Content ID", y); value(doc, r.contentId.toUpperCase(), y + 7); y += 24;
  footer(doc);
  doc.save(`${r.title.replace(/\s+/g, "_")}_One_Pager.pdf`);
}

export function splitSheetPdf(s: SplitSheetInput) {
  const doc = new jsPDF();

  // ── Cover block ──────────────────────────────────────────────────
  doc.setFillColor(10, 10, 12);
  doc.rect(0, 0, 210, 56, "F");
  doc.setTextColor(110); doc.setFont("courier", "normal"); doc.setFontSize(8);
  doc.text("MUSIC SPLIT SHEET · RIPPL MUSIC GROUP", 16, 18);
  doc.setTextColor(255); doc.setFont("courier", "bold"); doc.setFontSize(20);
  doc.text(s.trackTitle || "Untitled Track", 16, 32);
  doc.setFont("courier", "normal"); doc.setFontSize(9); doc.setTextColor(180);
  doc.text(`By ${s.artist || "—"}`, 16, 41);
  doc.text(`Prepared: ${s.date}`, 16, 48);
  doc.setDrawColor(255); doc.setLineWidth(0.8);
  doc.circle(192, 26, 1.6, "F");
  doc.line(192, 26, 192, 20); doc.line(192, 26, 198, 26);

  let y = 70;

  // ── Track metadata box ───────────────────────────────────────────
  doc.setFillColor(248, 248, 250); doc.rect(14, y - 4, 182, 28, "F");
  doc.setDrawColor(220); doc.setLineWidth(0.3); doc.rect(14, y - 4, 182, 28, "D");
  doc.setFont("courier", "normal"); doc.setFontSize(8); doc.setTextColor(100);
  const meta: [string, string][] = [
    ["ISRC",          s.isrc || "—"],
    ["ISWC",          s.iswc || "—"],
    ["RECORDING DATE",s.recordingDate || s.date],
    ["LABEL",         s.label || "Independent"],
    ["PUB. ADMIN",    s.publisher || "—"],
  ];
  let mx = 16;
  meta.forEach(([k, v], i) => {
    if (i === 3) { mx = 16; y += 13; }
    doc.text(k, mx, y); doc.setFont("courier", "bold"); doc.setTextColor(20);
    doc.text(v, mx, y + 5); doc.setFont("courier", "normal"); doc.setTextColor(100);
    mx += 38;
  });
  y += 24;

  // ── Master ownership table ───────────────────────────────────────
  y += 6;
  doc.setFillColor(20, 20, 24); doc.rect(14, y - 5, 182, 8, "F");
  doc.setFont("courier", "bold"); doc.setFontSize(8); doc.setTextColor(255);
  doc.text("MASTER RECORDING OWNERSHIP", 16, y);
  doc.text("ROLE", 100, y); doc.text("IPI / CAE", 130, y); doc.text("MASTER %", 168, y);
  y += 9;

  const masterTotal = s.entries.reduce((sum, e) => sum + (Number(e.masterPct) || 0), 0);
  s.entries.forEach((e, i) => {
    if (i % 2 === 0) { doc.setFillColor(252, 252, 254); doc.rect(14, y - 4, 182, 8, "F"); }
    doc.setFont("courier", "bold"); doc.setFontSize(9); doc.setTextColor(15);
    doc.text(e.name || "—", 16, y);
    doc.setFont("courier", "normal"); doc.setTextColor(60);
    doc.text(e.role || "—", 100, y);
    doc.text(e.ipi || "—", 130, y);
    doc.setFont("courier", "bold"); doc.setTextColor(15);
    doc.text(`${Number(e.masterPct) || 0}%`, 168, y);
    y += 8;
  });
  doc.setDrawColor(180); doc.setLineWidth(0.3); doc.line(14, y, 196, y); y += 6;
  doc.setFont("courier", "bold"); doc.setFontSize(9);
  const masterOk = masterTotal === 100;
  doc.setTextColor(masterOk ? 40 : 180, masterOk ? 120 : 40, masterOk ? 40 : 40);
  doc.text(`Master Total: ${masterTotal}%${!masterOk ? "  ⚠ Does not add up to 100%" : " ✓"}`, 130, y);
  y += 12;

  // ── Publishing / composition table ──────────────────────────────
  doc.setFillColor(20, 20, 24); doc.rect(14, y - 5, 182, 8, "F");
  doc.setFont("courier", "bold"); doc.setFontSize(8); doc.setTextColor(255);
  doc.text("PUBLISHING / COMPOSITION OWNERSHIP", 16, y);
  doc.text("PUBLISHING ADMIN", 100, y); doc.text("PUB %", 168, y);
  y += 9;

  const pubTotal = s.entries.reduce((sum, e) => sum + (Number(e.pubPct) || 0), 0);
  s.entries.forEach((e, i) => {
    if (i % 2 === 0) { doc.setFillColor(252, 252, 254); doc.rect(14, y - 4, 182, 8, "F"); }
    doc.setFont("courier", "bold"); doc.setFontSize(9); doc.setTextColor(15);
    doc.text(e.name || "—", 16, y);
    doc.setFont("courier", "normal"); doc.setTextColor(60);
    doc.text(e.publisher || "Self-published", 100, y);
    doc.setFont("courier", "bold"); doc.setTextColor(15);
    doc.text(`${Number(e.pubPct) || 0}%`, 168, y);
    y += 8;
  });
  doc.setDrawColor(180); doc.line(14, y, 196, y); y += 6;
  doc.setFont("courier", "bold"); doc.setFontSize(9);
  const pubOk = pubTotal === 100;
  doc.setTextColor(pubOk ? 40 : 180, pubOk ? 120 : 40, pubOk ? 40 : 40);
  doc.text(`Publishing Total: ${pubTotal}%${!pubOk ? "  ⚠ Does not add up to 100%" : " ✓"}`, 110, y);
  y += 16;

  // ── Legal declaration ────────────────────────────────────────────
  if (y > 220) { doc.addPage(); y = 24; }
  doc.setFillColor(245, 245, 248); doc.rect(14, y - 4, 182, 28, "F");
  doc.setFont("courier", "normal"); doc.setFontSize(8); doc.setTextColor(60);
  doc.text(doc.splitTextToSize(
    "DECLARATION: By signing this agreement, each party confirms that (i) the ownership percentages above are accurate and complete; " +
    "(ii) they have the authority to enter into this agreement; (iii) no third-party claims exist that would encumber the rights herein; " +
    "and (iv) royalties from NEIGHBORING RIGHTS will be distributed in proportion to the Master ownership percentages listed above, " +
    "unless separately agreed in writing. This document is legally binding upon execution by all parties.",
    178,
  ), 16, y + 2);
  y += 34;

  // ── Signature blocks ─────────────────────────────────────────────
  doc.setFont("courier", "bold"); doc.setFontSize(8); doc.setTextColor(60);
  doc.text("SIGNATURES", 16, y); y += 8;

  s.entries.forEach((e) => {
    if (y > 262) { doc.addPage(); y = 24; }
    doc.setFillColor(250, 250, 252); doc.rect(14, y - 3, 182, 22, "F");
    doc.setDrawColor(200); doc.rect(14, y - 3, 182, 22, "D");
    doc.setFont("courier", "bold"); doc.setFontSize(9); doc.setTextColor(15);
    doc.text(e.name || "Contributor", 16, y + 4);
    doc.setFont("courier", "normal"); doc.setFontSize(7); doc.setTextColor(100);
    doc.text(e.role || "—", 16, y + 9);
    if (e.email) doc.text(e.email, 16, y + 13);
    doc.setDrawColor(140); doc.line(90, y + 14, 160, y + 14);
    doc.text("Signature", 90, y + 17);
    doc.line(162, y + 14, 194, y + 14);
    doc.text("Date", 162, y + 17);
    y += 26;
  });

  footer(doc);
  doc.save(`${(s.trackTitle || "Split_Sheet").replace(/\s+/g, "_")}_Split_Sheet.pdf`);
}

/* RIPPL workplan §7: "Brief generator — once a campaign has creators +
   deliverables, generate a brief PDF that can be sent to each creator."

   Split into build (returns the jsPDF doc, no I/O) + save (browser download)
   so the exact same brief can be generated server-side too — the Monday
   digest cron (api/cron/weekly-digest.ts → src/lib/weekly-digest-sweep.ts)
   calls buildCampaignBriefDoc() directly and uploads doc.output("arraybuffer")
   to Storage instead of triggering a browser download. jsPDF has no DOM
   dependency for text-only docs like this one, so it runs fine in a Node
   serverless function. */
export function buildCampaignBriefDoc(c: Campaign, checklist: ChecklistPhase[], creatorNames: string[]): jsPDF {
  const doc = new jsPDF();
  header(doc, "Campaign Brief", `${c.artist} — ${c.title}`);
  let y = 62;
  label(doc, "Campaign", y); value(doc, c.title || "—", y + 7); y += 22;
  label(doc, "Artist", y); value(doc, c.artist || "—", y + 7); y += 22;
  label(doc, "Window", y); value(doc, `${c.startDate || "TBC"} → ${c.endDate || "TBC"}`, y + 7, 11); y += 22;
  label(doc, "Platforms", y); value(doc, (c.platforms ?? []).join(" · ") || "—", y + 7, 11); y += 22;
  label(doc, "Goal", y); value(doc, c.goal || "—", y + 7, 11); y += 24;

  if (creatorNames.length) {
    label(doc, `Creators on this campaign (${creatorNames.length})`, y); y += 8;
    doc.setTextColor(40); doc.setFont("courier", "normal"); doc.setFontSize(10);
    doc.text(doc.splitTextToSize(creatorNames.join(" · "), 178), 16, y);
    y += Math.ceil(creatorNames.join(" · ").length / 70) * 5 + 12;
  }

  if (checklist.length) {
    label(doc, "Rollout plan", y); y += 9;
    for (const phase of checklist) {
      if (y > 262) { doc.addPage(); y = 24; }
      doc.setTextColor(20); doc.setFont("courier", "bold"); doc.setFontSize(11);
      doc.text(phase.phase, 16, y); y += 7;
      doc.setFont("courier", "normal"); doc.setFontSize(9); doc.setTextColor(70);
      for (const item of phase.items) {
        if (y > 275) { doc.addPage(); y = 24; }
        doc.text(`[ ] ${item.label}`, 20, y); y += 5.5;
      }
      y += 5;
    }
  }
  footer(doc);
  return doc;
}

/** Browser-only: build the brief and trigger a download. Everything HQ's UI
 *  already calls (PlatformDashboard's "Download Brief" button) keeps using
 *  this unchanged. */
export function campaignBriefPdf(c: Campaign, checklist: ChecklistPhase[], creatorNames: string[]) {
  const doc = buildCampaignBriefDoc(c, checklist, creatorNames);
  doc.save(`${(c.title || "Campaign").replace(/\s+/g, "_")}_Brief.pdf`);
}
