import { jsPDF } from "jspdf";
import type { Artist, Release } from "./os-store";

/* Client-facing PDF generators (press kit, release one-pager). Minimal,
   monospace-ish, on-brand black/white layout. */

function header(doc: jsPDF, eyebrow: string, title: string) {
  doc.setFillColor(10, 10, 12); doc.rect(0, 0, 210, 46, "F");
  doc.setTextColor(150); doc.setFont("courier", "normal"); doc.setFontSize(9);
  doc.text(eyebrow.toUpperCase(), 16, 20);
  doc.setTextColor(255); doc.setFont("courier", "bold"); doc.setFontSize(22);
  doc.text(title, 16, 33);
  // ripple mark
  doc.setDrawColor(255); doc.setLineWidth(0.8);
  doc.circle(190, 23, 1.4, "F");
  doc.line(190, 23, 190, 18); doc.line(190, 23, 195, 23);
}
function footer(doc: jsPDF) {
  doc.setTextColor(150); doc.setFont("courier", "normal"); doc.setFontSize(8);
  doc.text("Generated by RIPPL · Built by Zeyad Sayedin · © 2026", 16, 288);
}
function label(doc: jsPDF, text: string, y: number) {
  doc.setTextColor(120); doc.setFont("courier", "normal"); doc.setFontSize(8);
  doc.text(text.toUpperCase(), 16, y);
}
function value(doc: jsPDF, text: string, y: number, size = 13) {
  doc.setTextColor(20); doc.setFont("courier", "bold"); doc.setFontSize(size);
  doc.text(text, 16, y);
}

export function pressKitPdf(a: Artist) {
  const doc = new jsPDF();
  header(doc, "Press Kit", a.name);
  let y = 62;
  label(doc, "Type", y); value(doc, a.kind, y + 7); y += 22;
  label(doc, "Handle", y); value(doc, a.handle || "—", y + 7); y += 22;
  label(doc, a.kind === "Music" ? "Streams" : "Followers", y); value(doc, (a.kind === "Music" ? a.streams : a.followers) || "—", y + 7, 20); y += 24;
  label(doc, "Stage", y); value(doc, a.stage, y + 7); y += 24;
  label(doc, "Bio / Notes", y); y += 8;
  doc.setTextColor(40); doc.setFont("courier", "normal"); doc.setFontSize(11);
  const bio = a.note || `${a.name} is a leading ${a.kind.toLowerCase()} talent managed by RIPPL, with strong regional pull across TikTok, Instagram and DSPs.`;
  doc.text(doc.splitTextToSize(bio, 178), 16, y);
  footer(doc);
  doc.save(`${a.name.replace(/\s+/g, "_")}_Press_Kit.pdf`);
}

export function releaseOnePagerPdf(r: Release) {
  const doc = new jsPDF();
  header(doc, "Release One-Pager", r.title);
  let y = 62;
  label(doc, "Artist", y); value(doc, r.artist || "—", y + 7); y += 22;
  label(doc, "Release date", y); value(doc, r.releaseDate || "TBC", y + 7); y += 22;
  const dsps = [r.dsp.spotify && "Spotify", r.dsp.anghami && "Anghami", r.dsp.youtube && "YouTube"].filter(Boolean).join(" · ") || "—";
  label(doc, "Available on", y); value(doc, dsps, y + 7); y += 22;
  label(doc, "ISRC / UPC", y); value(doc, `${r.isrc || "—"}  ·  ${r.upc || "—"}`, y + 7, 11); y += 22;
  label(doc, "Audio QA", y);
  value(doc, `Dolby Atmos ${r.qa.atmos ? "✓" : "—"}   Master EQ ${r.qa.eq ? "✓" : "—"}`, y + 7, 11); y += 24;
  label(doc, "Content ID", y); value(doc, r.contentId.toUpperCase(), y + 7); y += 24;
  footer(doc);
  doc.save(`${r.title.replace(/\s+/g, "_")}_One_Pager.pdf`);
}
