/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as TechlabRouteImport } from './routes/techlab'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SRouteImport } from './routes/s'
import { Route as RosterRouteImport } from './routes/roster'
import { Route as ReleasesRouteImport } from './routes/releases'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreatorsRouteImport } from './routes/creators'
import { Route as ChannelsRouteImport } from './routes/channels'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BudgetRouteImport } from './routes/budget'
import { Route as AudioRouteImport } from './routes/audio'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardYoutubeRouteImport } from './routes/dashboard_.youtube'
import { Route as DashboardXRouteImport } from './routes/dashboard_.x'
import { Route as DashboardTiktokRouteImport } from './routes/dashboard_.tiktok'
import { Route as DashboardInstagramRouteImport } from './routes/dashboard_.instagram'
import { Route as DashboardFacebookRouteImport } from './routes/dashboard_.facebook'
import { Route as CTokenRouteImport } from './routes/c.$token'

const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const TechlabRoute = TechlabRouteImport.update({
  id: '/techlab',
  path: '/techlab',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SRoute = SRouteImport.update({
  id: '/s',
  path: '/s',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterRoute = RosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleasesRoute = ReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsRoute = CreatorsRouteImport.update({
  id: '/creators',
  path: '/creators',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRoute = ChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetRoute = BudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioRoute = AudioRouteImport.update({
  id: '/audio',
  path: '/audio',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardYoutubeRoute = DashboardYoutubeRouteImport.update({
  id: '/dashboard_/youtube',
  path: '/dashboard/youtube',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardXRoute = DashboardXRouteImport.update({
  id: '/dashboard_/x',
  path: '/dashboard/x',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTiktokRoute = DashboardTiktokRouteImport.update({
  id: '/dashboard_/tiktok',
  path: '/dashboard/tiktok',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardInstagramRoute = DashboardInstagramRouteImport.update({
  id: '/dashboard_/instagram',
  path: '/dashboard/instagram',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFacebookRoute = DashboardFacebookRouteImport.update({
  id: '/dashboard_/facebook',
  path: '/dashboard/facebook',
  getParentRoute: () => rootRouteImport,
} as any)
const CTokenRoute = CTokenRouteImport.update({
  id: '/c/$token',
  path: '/c/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assets': typeof AssetsRoute
  '/audio': typeof AudioRoute
  '/budget': typeof BudgetRoute
  '/calendar': typeof CalendarRoute
  '/campaigns': typeof CampaignsRoute
  '/channels': typeof ChannelsRoute
  '/creators': typeof CreatorsRoute
  '/dashboard': typeof DashboardRoute
  '/home': typeof HomeRoute
  '/releases': typeof ReleasesRoute
  '/roster': typeof RosterRoute
  '/s': typeof SRoute
  '/settings': typeof SettingsRoute
  '/studio': typeof StudioRoute
  '/tasks': typeof TasksRoute
  '/techlab': typeof TechlabRoute
  '/templates': typeof TemplatesRoute
  '/vault': typeof VaultRoute
  '/c/$token': typeof CTokenRoute
  '/dashboard/facebook': typeof DashboardFacebookRoute
  '/dashboard/instagram': typeof DashboardInstagramRoute
  '/dashboard/tiktok': typeof DashboardTiktokRoute
  '/dashboard/x': typeof DashboardXRoute
  '/dashboard/youtube': typeof DashboardYoutubeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assets': typeof AssetsRoute
  '/audio': typeof AudioRoute
  '/budget': typeof BudgetRoute
  '/calendar': typeof CalendarRoute
  '/campaigns': typeof CampaignsRoute
  '/channels': typeof ChannelsRoute
  '/creators': typeof CreatorsRoute
  '/dashboard': typeof DashboardRoute
  '/home': typeof HomeRoute
  '/releases': typeof ReleasesRoute
  '/roster': typeof RosterRoute
  '/s': typeof SRoute
  '/settings': typeof SettingsRoute
  '/studio': typeof StudioRoute
  '/tasks': typeof TasksRoute
  '/techlab': typeof TechlabRoute
  '/templates': typeof TemplatesRoute
  '/vault': typeof VaultRoute
  '/c/$token': typeof CTokenRoute
  '/dashboard/facebook': typeof DashboardFacebookRoute
  '/dashboard/instagram': typeof DashboardInstagramRoute
  '/dashboard/tiktok': typeof DashboardTiktokRoute
  '/dashboard/x': typeof DashboardXRoute
  '/dashboard/youtube': typeof DashboardYoutubeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assets': typeof AssetsRoute
  '/audio': typeof AudioRoute
  '/budget': typeof BudgetRoute
  '/calendar': typeof CalendarRoute
  '/campaigns': typeof CampaignsRoute
  '/channels': typeof ChannelsRoute
  '/creators': typeof CreatorsRoute
  '/dashboard': typeof DashboardRoute
  '/home': typeof HomeRoute
  '/releases': typeof ReleasesRoute
  '/roster': typeof RosterRoute
  '/s': typeof SRoute
  '/settings': typeof SettingsRoute
  '/studio': typeof StudioRoute
  '/tasks': typeof TasksRoute
  '/techlab': typeof TechlabRoute
  '/templates': typeof TemplatesRoute
  '/vault': typeof VaultRoute
  '/c/$token': typeof CTokenRoute
  '/dashboard_/facebook': typeof DashboardFacebookRoute
  '/dashboard_/instagram': typeof DashboardInstagramRoute
  '/dashboard_/tiktok': typeof DashboardTiktokRoute
  '/dashboard_/x': typeof DashboardXRoute
  '/dashboard_/youtube': typeof DashboardYoutubeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/assets'
    | '/audio'
    | '/budget'
    | '/calendar'
    | '/campaigns'
    | '/channels'
    | '/creators'
    | '/dashboard'
    | '/home'
    | '/releases'
    | '/roster'
    | '/s'
    | '/settings'
    | '/studio'
    | '/tasks'
    | '/techlab'
    | '/templates'
    | '/vault'
    | '/c/$token'
    | '/dashboard/facebook'
    | '/dashboard/instagram'
    | '/dashboard/tiktok'
    | '/dashboard/x'
    | '/dashboard/youtube'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/assets'
    | '/audio'
    | '/budget'
    | '/calendar'
    | '/campaigns'
    | '/channels'
    | '/creators'
    | '/dashboard'
    | '/home'
    | '/releases'
    | '/roster'
    | '/s'
    | '/settings'
    | '/studio'
    | '/tasks'
    | '/techlab'
    | '/templates'
    | '/vault'
    | '/c/$token'
    | '/dashboard/facebook'
    | '/dashboard/instagram'
    | '/dashboard/tiktok'
    | '/dashboard/x'
    | '/dashboard/youtube'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/assets'
    | '/audio'
    | '/budget'
    | '/calendar'
    | '/campaigns'
    | '/channels'
    | '/creators'
    | '/dashboard'
    | '/home'
    | '/releases'
    | '/roster'
    | '/s'
    | '/settings'
    | '/studio'
    | '/tasks'
    | '/techlab'
    | '/templates'
    | '/vault'
    | '/c/$token'
    | '/dashboard_/facebook'
    | '/dashboard_/instagram'
    | '/dashboard_/tiktok'
    | '/dashboard_/x'
    | '/dashboard_/youtube'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AssetsRoute: typeof AssetsRoute
  AudioRoute: typeof AudioRoute
  BudgetRoute: typeof BudgetRoute
  CalendarRoute: typeof CalendarRoute
  CampaignsRoute: typeof CampaignsRoute
  ChannelsRoute: typeof ChannelsRoute
  CreatorsRoute: typeof CreatorsRoute
  DashboardRoute: typeof DashboardRoute
  HomeRoute: typeof HomeRoute
  ReleasesRoute: typeof ReleasesRoute
  RosterRoute: typeof RosterRoute
  SRoute: typeof SRoute
  SettingsRoute: typeof SettingsRoute
  StudioRoute: typeof StudioRoute
  TasksRoute: typeof TasksRoute
  TechlabRoute: typeof TechlabRoute
  TemplatesRoute: typeof TemplatesRoute
  VaultRoute: typeof VaultRoute
  CTokenRoute: typeof CTokenRoute
  DashboardFacebookRoute: typeof DashboardFacebookRoute
  DashboardInstagramRoute: typeof DashboardInstagramRoute
  DashboardTiktokRoute: typeof DashboardTiktokRoute
  DashboardXRoute: typeof DashboardXRoute
  DashboardYoutubeRoute: typeof DashboardYoutubeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/techlab': {
      id: '/techlab'
      path: '/techlab'
      fullPath: '/techlab'
      preLoaderRoute: typeof TechlabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s': {
      id: '/s'
      path: '/s'
      fullPath: '/s'
      preLoaderRoute: typeof SRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster': {
      id: '/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof RosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/releases': {
      id: '/releases'
      path: '/releases'
      fullPath: '/releases'
      preLoaderRoute: typeof ReleasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators': {
      id: '/creators'
      path: '/creators'
      fullPath: '/creators'
      preLoaderRoute: typeof CreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio': {
      id: '/audio'
      path: '/audio'
      fullPath: '/audio'
      preLoaderRoute: typeof AudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/youtube': {
      id: '/dashboard_/youtube'
      path: '/dashboard/youtube'
      fullPath: '/dashboard/youtube'
      preLoaderRoute: typeof DashboardYoutubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/x': {
      id: '/dashboard_/x'
      path: '/dashboard/x'
      fullPath: '/dashboard/x'
      preLoaderRoute: typeof DashboardXRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/tiktok': {
      id: '/dashboard_/tiktok'
      path: '/dashboard/tiktok'
      fullPath: '/dashboard/tiktok'
      preLoaderRoute: typeof DashboardTiktokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/instagram': {
      id: '/dashboard_/instagram'
      path: '/dashboard/instagram'
      fullPath: '/dashboard/instagram'
      preLoaderRoute: typeof DashboardInstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/facebook': {
      id: '/dashboard_/facebook'
      path: '/dashboard/facebook'
      fullPath: '/dashboard/facebook'
      preLoaderRoute: typeof DashboardFacebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$token': {
      id: '/c/$token'
      path: '/c/$token'
      fullPath: '/c/$token'
      preLoaderRoute: typeof CTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AssetsRoute: AssetsRoute,
  AudioRoute: AudioRoute,
  BudgetRoute: BudgetRoute,
  CalendarRoute: CalendarRoute,
  CampaignsRoute: CampaignsRoute,
  ChannelsRoute: ChannelsRoute,
  CreatorsRoute: CreatorsRoute,
  DashboardRoute: DashboardRoute,
  HomeRoute: HomeRoute,
  ReleasesRoute: ReleasesRoute,
  RosterRoute: RosterRoute,
  SRoute: SRoute,
  SettingsRoute: SettingsRoute,
  StudioRoute: StudioRoute,
  TasksRoute: TasksRoute,
  TechlabRoute: TechlabRoute,
  TemplatesRoute: TemplatesRoute,
  VaultRoute: VaultRoute,
  CTokenRoute: CTokenRoute,
  DashboardFacebookRoute: DashboardFacebookRoute,
  DashboardInstagramRoute: DashboardInstagramRoute,
  DashboardTiktokRoute: DashboardTiktokRoute,
  DashboardXRoute: DashboardXRoute,
  DashboardYoutubeRoute: DashboardYoutubeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
